# Generated by Django 4.2 on 2026-03-05 06:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('domain', models.CharField(max_length=255)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('page_load_time_ms', models.IntegerField(blank=True, null=True)),
                ('page_size_mb', models.FloatField(blank=True, null=True)),
                ('total_requests', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('title_length', models.IntegerField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_description_length', models.IntegerField(blank=True, null=True)),
                ('h1_count', models.IntegerField(blank=True, null=True)),
                ('h2_count', models.IntegerField(blank=True, null=True)),
                ('canonical_tag', models.URLField(blank=True, null=True)),
                ('robots_meta_tag', models.CharField(blank=True, max_length=200)),
                ('og_title', models.CharField(blank=True, max_length=500)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('sitemap_exists', models.BooleanField(default=False)),
                ('sitemap_url', models.URLField(blank=True, null=True)),
                ('robots_txt_exists', models.BooleanField(default=False)),
                ('total_links', models.IntegerField(blank=True, null=True)),
                ('internal_links', models.IntegerField(blank=True, null=True)),
                ('external_links', models.IntegerField(blank=True, null=True)),
                ('broken_links', models.IntegerField(blank=True, null=True)),
                ('redirects_count', models.IntegerField(blank=True, null=True)),
                ('total_images', models.IntegerField(blank=True, null=True)),
                ('broken_images', models.IntegerField(blank=True, null=True)),
                ('images_missing_alt', models.IntegerField(blank=True, null=True)),
                ('https_enabled', models.BooleanField(default=False)),
                ('ssl_grade', models.CharField(blank=True, max_length=20)),
                ('security_headers', models.JSONField(default=dict)),
                ('missing_headers', models.JSONField(default=list)),
                ('has_viewport_meta', models.BooleanField(default=False)),
                ('is_mobile_friendly', models.BooleanField(default=False)),
                ('missing_lang_attribute', models.BooleanField(default=False)),
                ('full_analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_links_list', to='audit_api.auditresult')),
            ],
        ),
        migrations.CreateModel(
            name='BrokenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_images_list', to='audit_api.auditresult')),
            ],
        ),
        migrations.AddField(
            model_name='auditresult',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='audit_api.audittask'),
        ),
    ]
