# Generated by Django 4.2 on 2026-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_api', '0002_auditreporterinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreporterinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
